//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceipt
    {
        public int fldReceiptID { get; set; }
        public Nullable<int> fldUserID { get; set; }
        public Nullable<int> fldTripID { get; set; }
        public Nullable<double> fldProjectedValue { get; set; }
        public Nullable<double> fldAmountPaid { get; set; }
    
        public virtual tblTrip tblTrip { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
