//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserToGroup
    {
        public int fldUserToGroupID { get; set; }
        public Nullable<int> fldUserID { get; set; }
        public Nullable<int> fldGroupID { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
